FROM golang:1

ENV PROJECT=concept-rw-elasticsearch

COPY go.mod /
COPY go.sum /
RUN go mod download

COPY . /${PROJECT}/
WORKDIR /${PROJECT}

RUN echo "Fetching dependencies..." \
  && wget https://raw.githubusercontent.com/eficode/wait-for/master/wait-for \
  && chmod +x wait-for

ENTRYPOINT ["./wait-for", "elastic-search:9200", "-t", "60", "--"]
